#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the anagram function below.
def anagram(s):
    if len(s)%2==1:
        return -1
    d1={}
    for i in range(len(s)//2):
        if s[i] not in d1:
            d1[s[i]]=0
        d1[s[i]]+=1
    d2={}
    for i in range(len(s)//2,len(s)):
        if s[i] not in d2:
            d2[s[i]]=0
        d2[s[i]]+=1
    c=0
    for k,v in d1.items():
        if k not in d2:
            c+=v
        else:
            temp=d2[k]
            if v>temp:
                c+=v-temp
    return c

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = anagram(s)

        fptr.write(str(result) + '\n')

    fptr.close()
