#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the candies function below.
def candies(n, arr):
    inc=[1]*n
    dec=[1]*n
    #fwd[-1]=1
    for i in range(1,n):
        if arr[i]>arr[i-1]:
            inc[i]=inc[i-1]+1
    for i in range(n-2,-1,-1):
        if arr[i]>arr[i+1]:
            dec[i]=dec[i+1]+1
    res=0
    for i in range(n):
        res+=max(inc[i],dec[i])
    return res
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = []

    for _ in range(n):
        arr_item = int(input())
        arr.append(arr_item)

    result = candies(n, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
