#!/bin/python3

import os
import sys

#
# Complete the equalStacks function below.
#
def equalStacks(h1, h2, h3):
    #
    # Write your code here.
    #
    s1=sum(h1)
    s2=sum(h2)
    s3=sum(h3)
    i=0
    j=0
    k=0
    while i<len(h1) and j<len(h2) and k<len(h3):
        if s1==s2==s3:
            return s1
        if s1>s2:
            if s3>s1:
                s3-=h3[k]
                k+=1
            else:
                s1-=h1[i]
                i+=1
        else:
            if s3>s2:
                s3-=h3[k]
                k+=1
            else:
                s2-=h2[j]
                j+=1
    return 0
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n1N2N3 = input().split()

    n1 = int(n1N2N3[0])

    n2 = int(n1N2N3[1])

    n3 = int(n1N2N3[2])

    h1 = list(map(int, input().rstrip().split()))

    h2 = list(map(int, input().rstrip().split()))

    h3 = list(map(int, input().rstrip().split()))

    result = equalStacks(h1, h2, h3)

    fptr.write(str(result) + '\n')

    fptr.close()
