#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the decentNumber function below.
def decentNumber(n):
    t=n
    f=True
    while t%3!=0:
        t-=5
        if t<0:
            print(-1)
            f=False
            break
    #print(t,n-t)
    if f:
        print('5'*t+'3'*(n-t))
    #return '5'*t+'3'*(n-t)

if __name__ == '__main__':
    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        decentNumber(n)
